#!/bin/sh

if [ ! -z "$DEBUG" ]; then
    function dbg() { echo $1; };
else
    function dbg() { return; };
fi

# Check if command was ran as root.
if [ $(id -u) -eq 0 ]; then
    echo "The command $(basename $0) should *not be executed as root* or using sudo." 1>&2
    echo "When a service requires root access, you will be prompted for a password as needed." 1>&2
    exit -1
fi

# Print usage
if [ $# -ne 1 ]; then
    echo "Usage: $(basename $0) [phpversion]"
    
    echo "Available PHP versions:"
    for ver_num in $(brew list | grep '^php[0-9]\{2,\}$' | grep -o -E '[0-9]+'); do
        echo " - $ver_num"
    done
    exit -2
fi

CURRENT_FPM=$(launchctl list | grep php | awk -F'[^0-9]*' '{print $3}')
NEW_FPM="$1"

# Check if a version is loaded
if [ -z "$CURRENT_FPM" ]; then
    echo "\nWARNING: No current php version loaded" 1>&2

# Check if new version is already the current version.
elif [ "$CURRENT_FPM" = "$NEW_FPM" ]; then
    echo "NOTICE: PHP version $NEW_FPM already active."
    while true; do
        read -r -p "Continue anyway? (y/n) " yn
        case $yn in
            [Yy]* ) echo && break;;
            [Nn]* ) echo && exit 0;;
        esac
    done

else
    dbg "Attempting to swap between php$CURRENT_FPM and php$NEW_FPM"
fi

# Check if the required version exists
brew list php$NEW_FPM >/dev/null 2>&1
if [ $? -eq 0 ]; then
    LAUNCHAGENTS_DIR="/Users/$(id -u -n)/Library/LaunchAgents"

    CUR_PLIST_NAME="homebrew.mxcl.php$CURRENT_FPM.plist"
    NEW_PLIST_NAME="homebrew.mxcl.php$NEW_FPM.plist"

    CUR_PLIST_LINK="$LAUNCHAGENTS_DIR/$CUR_PLIST_NAME"
    NEW_PLIST_LINK="$LAUNCHAGENTS_DIR/$NEW_PLIST_NAME"
    NEW_PLIST_FILE="/usr/local/opt/php$NEW_FPM/$NEW_PLIST_NAME"

    # Exit if the new LaunchAgent is not available
    if [ ! -f "$NEW_PLIST_FILE" ]; then
        echo "\nERROR: Missing php-fpm launchtl file for version: $NEW_FPM" 1>&2
        exit -2;
    fi
    
    # To prevent issues only act if the LaunchAgent is a Symlink
    if [ -e "$CUR_PLIST_LINK" -a ! -L "$CUR_PLIST_LINK" ]; then
        echo "\nERROR: Current LaunchAgent is not a Symlink aborting as saefty measure." 1>&2
        echo "Please make sure that php-fpm LaunchAgents are symlinks to the brew-generated files."
        echo "LaunchAgent plist file is: $CUR_PLIST_LINK"
        exit -3;
    fi

    # Unload current LaunchAgent (if any)
    if [ ! -z "$CURRENT_FPM" ]; then
        dbg "Unloading php-fpm $CURRENT_FPM service."
        launchctl unload -w "$CUR_PLIST_LINK"
    fi

    if [ -e "$CUR_PLIST_LINK" ]; then
        dbg "Unlinking old LaunchAgent"
        /bin/rm "$CUR_PLIST_LINK"
    fi

    # Link new Agent 
    dbg "Linking new LaunchAgent"
    /bin/ln -s "$NEW_PLIST_FILE" "$NEW_PLIST_LINK"

    # Load new PHP-FPM agent
    dbg "Loading php-fpm $FPM_NEW service"
    launchctl load -w "$NEW_PLIST_LINK"

    dbg "Open http://localhost/ and verify that the fpm version is successfully changed"
    echo "All Done!"

else
    echo "PHP version $NEW_FPM was not found." >&2
    echo "Try installing it: brew install php$NEW_FPM" >&2
    exit -10
fi
